### ISSUE TITLE
nofile limits does not correspond to documented scaling tier

### ISSUE THREAD

**Issue by hholst80** [SolaceLabs/solace-single-docker-compose#7]
The ulimits for nofile does not correspond to a scaling tier in the table in the documentation. 

https://docs.solace.com/Configuring-and-Managing/SW-Broker-Specific-Config/Docker-Tasks/Config-Docker-Create-Options.htm#shm-size

```
     ulimits:
       core: 1
       nofile:
         soft: 2448
         hard: 38048
```
